// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function App$Sync(props) {
  return JsxRuntime.jsx("button", {
              children: "Load / Save",
              className: "btn btn-primary"
            });
}

var Sync = {
  make: App$Sync
};

function App$Tools(props) {
  return JsxRuntime.jsx("ul", {
              children: JsxRuntime.jsx("li", {
                    children: JsxRuntime.jsx(App$Sync, {})
                  }),
              className: "menu menu-horizontal"
            });
}

var Tools = {
  make: App$Tools
};

function App(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(App$Tools, {}),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("table", {
                            children: [
                              JsxRuntime.jsx("thead", {
                                    children: JsxRuntime.jsxs("tr", {
                                          children: [
                                            JsxRuntime.jsx("th", {
                                                  children: JsxRuntime.jsx("label", {
                                                        children: JsxRuntime.jsx("input", {
                                                              className: "checkbox",
                                                              type: "checkbox"
                                                            })
                                                      })
                                                }),
                                            JsxRuntime.jsx("th", {
                                                  children: "Name"
                                                }),
                                            JsxRuntime.jsx("th", {
                                                  children: "Job"
                                                }),
                                            JsxRuntime.jsx("th", {
                                                  children: "Favorite Color"
                                                }),
                                            JsxRuntime.jsx("th", {})
                                          ]
                                        })
                                  }),
                              JsxRuntime.jsx("tbody", {
                                    children: JsxRuntime.jsxs("tr", {
                                          children: [
                                            JsxRuntime.jsx("th", {
                                                  children: JsxRuntime.jsx("label", {
                                                        children: JsxRuntime.jsx("input", {
                                                              className: "checkbox",
                                                              type: "checkbox"
                                                            })
                                                      })
                                                }),
                                            JsxRuntime.jsx("td", {
                                                  children: JsxRuntime.jsxs("div", {
                                                        children: [
                                                          JsxRuntime.jsx("div", {
                                                                children: JsxRuntime.jsx("div", {
                                                                      children: JsxRuntime.jsx("img", {
                                                                            alt: "Avatar Tailwind CSS Component",
                                                                            src: "https://img.daisyui.com/images/profile/demo/2@94.webp"
                                                                          }),
                                                                      className: "mask mask-squircle h-12 w-12"
                                                                    }),
                                                                className: "avatar"
                                                              }),
                                                          JsxRuntime.jsxs("div", {
                                                                children: [
                                                                  JsxRuntime.jsx("div", {
                                                                        children: "Hart Hagerty",
                                                                        className: "font-bold"
                                                                      }),
                                                                  JsxRuntime.jsx("div", {
                                                                        children: "United States",
                                                                        className: "text-sm opacity-50"
                                                                      })
                                                                ]
                                                              })
                                                        ],
                                                        className: "flex items-center gap-3"
                                                      })
                                                }),
                                            JsxRuntime.jsxs("td", {
                                                  children: [
                                                    "Zemlak, Daniel and Leannon",
                                                    JsxRuntime.jsx("br", {}),
                                                    JsxRuntime.jsx("span", {
                                                          children: "Desktop Support Technician",
                                                          className: "badge badge-ghost badge-sm"
                                                        })
                                                  ]
                                                }),
                                            JsxRuntime.jsx("td", {
                                                  children: "Purple"
                                                }),
                                            JsxRuntime.jsx("th", {
                                                  children: JsxRuntime.jsx("button", {
                                                        children: "details",
                                                        className: "btn btn-ghost btn-xs"
                                                      })
                                                })
                                          ]
                                        })
                                  }),
                              JsxRuntime.jsx("tfoot", {
                                    children: JsxRuntime.jsxs("tr", {
                                          children: [
                                            JsxRuntime.jsx("th", {}),
                                            JsxRuntime.jsx("th", {
                                                  children: "Name"
                                                }),
                                            JsxRuntime.jsx("th", {
                                                  children: "Job"
                                                }),
                                            JsxRuntime.jsx("th", {
                                                  children: "Favorite Color"
                                                }),
                                            JsxRuntime.jsx("th", {})
                                          ]
                                        })
                                  })
                            ],
                            className: "table"
                          }),
                      className: "overflow-x-auto"
                    })
              ]
            });
}

var make = App;

export {
  Sync ,
  Tools ,
  make ,
}
/* react/jsx-runtime Not a pure module */
