// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Client from "@libsql/client";

function local(path) {
  return Client.createClient({
              url: "file:" + path
            });
}

export {
  local ,
}
/* @libsql/client Not a pure module */
