// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DB from "./DB.res.mjs";
import * as Express from "express";
import Express$1 from "express";

var app = Express$1();

app.use(Express.json());

app.use(Express.static("public"));

app.get("/db", (async function (_req, res) {
        var c = DB.local("local.db");
        var r = await c.execute("SELECT * FROM beans;");
        console.log(r);
        res.status(200).json({
              result: r,
              details: ({"rows": r.rows, "columns": r.columns})
            });
      }));

app.use(function (err, _req, res, _next) {
      console.error(err);
      res.status(500).end("An error occurred");
    });

app.listen(8081, (function (param) {
        console.log("Listening on http://localhost:" + String(8081));
      }));

var port = 8081;

export {
  app ,
  port ,
}
/* app Not a pure module */
